all:
  hosts:
    server1:
      ansible_host: 172.21.21.79
      ansible_user: ubuntu
    server2:
      ansible_host: 192.168.1.11
      ansible_user: ubuntu

  children:
    webservers:
      hosts:
        server1:

    dbservers:
      hosts:
        server2:

